# Generated by Django 4.0.6 on 2022-08-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='font_size',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
