# Generated by Django 4.0.6 on 2022-08-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
    ]
